// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	models "mini-project/models"

	mock "github.com/stretchr/testify/mock"
)

// CategoryRepository is an autogenerated mock type for the CategoryRepository type
type CategoryRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: categoryRequest
func (_m *CategoryRepository) Create(categoryRequest models.CategoryRequest) models.Category {
	ret := _m.Called(categoryRequest)

	var r0 models.Category
	if rf, ok := ret.Get(0).(func(models.CategoryRequest) models.Category); ok {
		r0 = rf(categoryRequest)
	} else {
		r0 = ret.Get(0).(models.Category)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *CategoryRepository) Delete(id int) bool {
	ret := _m.Called(id)

	var r0 bool
	if rf, ok := ret.Get(0).(func(int) bool); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// GetAll provides a mock function with given fields:
func (_m *CategoryRepository) GetAll() []models.Category {
	ret := _m.Called()

	var r0 []models.Category
	if rf, ok := ret.Get(0).(func() []models.Category); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Category)
		}
	}

	return r0
}

// GetByID provides a mock function with given fields: id
func (_m *CategoryRepository) GetByID(id int) models.Category {
	ret := _m.Called(id)

	var r0 models.Category
	if rf, ok := ret.Get(0).(func(int) models.Category); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(models.Category)
	}

	return r0
}

// Update provides a mock function with given fields: id, categoryRequest
func (_m *CategoryRepository) Update(id int, categoryRequest models.CategoryRequest) models.Category {
	ret := _m.Called(id, categoryRequest)

	var r0 models.Category
	if rf, ok := ret.Get(0).(func(int, models.CategoryRequest) models.Category); ok {
		r0 = rf(id, categoryRequest)
	} else {
		r0 = ret.Get(0).(models.Category)
	}

	return r0
}

type mockConstructorTestingTNewCategoryRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewCategoryRepository creates a new instance of CategoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCategoryRepository(t mockConstructorTestingTNewCategoryRepository) *CategoryRepository {
	mock := &CategoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
