// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	models "mini-project/models"

	mock "github.com/stretchr/testify/mock"
)

// RoleRepository is an autogenerated mock type for the RoleRepository type
type RoleRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: roleRequest
func (_m *RoleRepository) Create(roleRequest models.RoleRequest) models.Role {
	ret := _m.Called(roleRequest)

	var r0 models.Role
	if rf, ok := ret.Get(0).(func(models.RoleRequest) models.Role); ok {
		r0 = rf(roleRequest)
	} else {
		r0 = ret.Get(0).(models.Role)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *RoleRepository) Delete(id int) bool {
	ret := _m.Called(id)

	var r0 bool
	if rf, ok := ret.Get(0).(func(int) bool); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// GetAll provides a mock function with given fields:
func (_m *RoleRepository) GetAll() []models.Role {
	ret := _m.Called()

	var r0 []models.Role
	if rf, ok := ret.Get(0).(func() []models.Role); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Role)
		}
	}

	return r0
}

// GetByID provides a mock function with given fields: id
func (_m *RoleRepository) GetByID(id int) models.Role {
	ret := _m.Called(id)

	var r0 models.Role
	if rf, ok := ret.Get(0).(func(int) models.Role); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(models.Role)
	}

	return r0
}

// Update provides a mock function with given fields: id, roleRequest
func (_m *RoleRepository) Update(id int, roleRequest models.RoleRequest) models.Role {
	ret := _m.Called(id, roleRequest)

	var r0 models.Role
	if rf, ok := ret.Get(0).(func(int, models.RoleRequest) models.Role); ok {
		r0 = rf(id, roleRequest)
	} else {
		r0 = ret.Get(0).(models.Role)
	}

	return r0
}

type mockConstructorTestingTNewRoleRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRoleRepository creates a new instance of RoleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRoleRepository(t mockConstructorTestingTNewRoleRepository) *RoleRepository {
	mock := &RoleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
